#!/usr/bin/env bash
#
# Format the titles somewhat nicely
#
# Author: Dave Eddy <ysap@daveeddy.com>
# Date: December 03, 2025
# License: MIT

for f in */readme.md; do
	IFS=- read -r chapter section _ <<< "$f"
	title=$(head -1 < "$f")
	title=${title#\# }

	echo "Chapter $chapter Section $section: $title"
done
